# -*- coding: utf-8 -*-
"""Python_intro.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lTGOK5g0rXGik6ecGrFezJJcsqpmY1GQ

Python Pandas Intro
"""

# prompt: install pandas library

!pip install pandas

import pandas as pd

df=pd.read_csv("/content/Salaries.csv")

df.head(10)

df.tail(10)

df.head(10)
df.head(50)

df.dtypes

df.dtypes

df.columns

df.axes

df.ndim

df.size

df.shape

df.values

df.size

df.axes

df.shape

df.columns

"""Data Frames methods"""

df.head(10)

df.tail(50)

df.describe()

df.max()

df.min()

df.mean()

df.median()

df.std()

df.sample(50)

df.dropna()

df

df.describe()

df.values

df

df.describe()

mean50=df.head(50)
mean50.mean()

df.head(50).mean()

df.phd

df["rank"]

df[["rank"]]

df.phd.describe()



df

df.groupby(["rank"]).mean()

df.groupby("rank")["salary"].mean()

df

df["salary"]>120000

df[df["salary"]>120000]

dfmale=df[df["sex"]=="Male"]
dfmale

dfmale[dfmale["salary"]>120000]

df.iloc[:,0:2]

df.iloc[1:3,0:2]

df.iloc[[0,5],[1,3]]

df

df.iloc[[12,15],[3,3]]

df.iloc[0:10]

df.iloc[0:3]

df.iloc[:,4:6]

df.iloc[60:61]

df.iloc[[0,2]]



"""Aggregation function in Pandas"""

df[["phd","salary"]].agg(["min","mean","max"])

df.kurt()

df.skew()

















